name: Terraform Workflow

on: 
    push:
        branches:
        - main
    pull_request: 
        branches:
        - main
    workflow_dispatch: 
        inputs:
            environment:
                description: 'Terraform version'
                required: true
                default: '1.10.3'
            
jobs:
    TFLint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Cache plugin dir
              uses: actions/cache@v2
              with:
                path: ~/.tflint.d/plugins
                key: ubuntu-latest-tflint-${{ hashFiles('**/tflint.hcl') }}

            - name: Setup TFLint
              uses: tflint-action@v4
              with:
                  version: latest

            - name: Show TFLint version
              run: tflint --version

            - name: Run TFLint
              run: tflint
    ci:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3
              with:
                  terraform_version: ${{ github.event.inputs.environment }}

            - name: Show Terraform version
              run: terraform -version

            - name: Terraform Init
              run: terraform init

            - name: Terraform Format
              run: terraform fmt -check -recursive

            - name: Terraform Validate
              run: terraform validate

            - name: Terraform Plan
              id: plan
              run: |
                    terraform plan -var-file=${{ github.ref_name }}/terraform.tfvars -out=tfplan
              env:
                  TF_VAR_environment: ${{ github.ref_name }}

            - name: Upload Plan as Artifact
              uses: actions/upload-artifact@v3
              with:
                  name: tfplan
                  path: tfplan


                  